apiVersion: v1
kind: Service
metadata:
  name: excel-pdf-service
spec:
  selector:
    app: excel-pdf-formatter
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excel-pdf-formatter
spec:
  selector:
    matchLabels:
      app: excel-pdf-formatter
  replicas: 1
  template:
    metadata:
      labels:
        app: excel-pdf-formatter
    spec:
      containers:
        - name: excel-pdf-formatter
          image: jatchet/excel-pdf-formatter:version1.0
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 200Mi
            limits:
              memory: 256Mi
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz/live
              port: 5000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz/ready
              port: 5000
            initialDelaySeconds: 5
